const Data = [
  {
    id: 1,
    qty: 1,
    title: "Entertainment Center",
    type: "kids",
    rate: 3,
    sku: "RecZkNf2kwmdBcqd0",
    brand: "liddy",
    img: require("./Img/product1.jpg"),
    price: 299.99,
    available: "in Stock",
    colors: ["black", "green"],
    freeShipping: true,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 2,
    qty: 1,
    brand: "liddy",
    sku: "RecZkNf2kwmdBcqd0",
    title: "High-Back Bench",
    type: "kids",
    freeShipping: true,
    rate: 3,
    colors: ["yellow", "black"],
    available: "in Stock",
    img: require("./Img/product2.jpg"),
    price: 519.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 3,
    qty: 1,
    sku: "RecZkNf2kwmdBcqd0",
    colors: ["green"],
    brand: "Ikea",
    title: "Modern Bookshelf",
    freeShipping: true,
    type: "living room",
    rate: 3,
    available: "in Stock",
    img: require("./Img/product3.jpg"),
    price: 199.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 4,
    qty: 1,
    sku: "RecZkNf2kwmdBcqd0",
    freeShipping: true,
    title: "Modern Bookshelf",
    colors: ["green"],
    type: "kids",
    brand: "Ikea",
    rate: 3,
    available: "in Stock",
    img: require("./Img/one.jpg"),
    freeShipping: true,
    price: 1299.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 5,
    qty: 1,
    sku: "RecZkNf2kwmdBcqd0",
    brand: "marcos",
    title: "Modern Bookshelf",
    freeShipping: true,
    type: "living room",
    rate: 3,
    available: "in Stock",
    img: require("./Img/two.jpg"),
    colors: ["red"],
    price: 299.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 6,
    qty: 1,
    sku: "RecZkNf2kwmdBcqd0",
    colors: ["gray", "black", "orange"],
    brand: "Ikea",
    freeShipping: false,
    title: "Modern Bookshelf",
    type: "living room",
    rate: 3,
    brand: "marcos",
    img: require("./Img/three.jpg"),
    price: 399.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
    available: "in Stock",
  },
  {
    id: 7,
    sku: "RecZkNf2kwmdBcqd0",
    freeShipping: false,
    colors: ["black", "green"],
    qty: 1,
    brand: "marcos",
    title: "Modern Bookshelf",
    type: "kids",
    rate: 3,

    available: "in Stock",
    img: require("./Img/four.jpg"),
    price: 339.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 8,
    sku: "RecZkNf2kwmdBcqd0",
    qty: 1,
    title: "Modern Bookshelf",
    type: "office",
    rate: 3,
    freeShipping: false,
    brand: "marcos",
    available: "in Stock",
    img: require("./Img/five.jpg"),
    colors: ["green"],
    price: 359.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 9,
    qty: 1,
    title: "Modern Bookshelf",
    type: "office",
    rate: 3,
    freeShipping: false,
    sku: "RecZkNf2kwmdBcqd0",
    brand: "Ikea",
    available: "in Stock",
    img: require("./Img/six.jpg"),
    colors: ["red", "blue", "green"],
    price: 3449.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 10,
    qty: 1,
    freeShipping: false,
    sku: "RecZkNf2kwmdBcqd0",
    title: "Modern Bookshelf",
    type: "office",
    rate: 3,
    brand: "marcos",
    available: "in Stock",
    img: require("./Img/seven.jpg"),
    colors: ["red", "yellow"],
    price: 799.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 11,
    qty: 1,
    freeShipping: false,
    sku: "RecZkNf2kwmdBcqd0",
    title: "Modern Bookshelf",
    colors: ["red", "blue", "green"],
    type: "office",
    rate: 3,
    available: "in Stock",
    img: require("./Img/eight.jpg"),
    price: 799.99,
    brand: "liddy",
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 12,
    freeShipping: false,
    qty: 1,
    available: "in Stock",
    title: "Modern Bookshelf",
    type: "kitchen",
    rate: 3,
    freeShipping: false,
    sku: "RecZkNf2kwmdBcqd0",
    brand: "caressa",
    img: require("./Img/nine.jpg"),
    colors: ["green"],
    price: 299.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 13,
    freeShipping: true,
    qty: 1,
    sku: "RecZkNf2kwmdBcqd0",
    available: "in Stock",
    title: "Modern Bookshelf",
    type: "kitchen",
    rate: 3,
    colors: ["red", "blue", "green"],
    brand: "Ikea",
    img: require("./Img/ten.jpg"),
    price: 429.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 14,
    brand: "caressa",
    sku: "RecZkNf2kwmdBcqd0",
    available: "in Stock",
    qty: 1,
    title: "Modern Bookshelf",
    type: "kitchen",
    freeShipping: true,
    rate: 3,
    img: require("./Img/eleven.jpg"),
    colors: ["red", "blue", "gray", "orange"],
    price: 99.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 15,
    brand: "caressa",
    sku: "RecZkNf2kwmdBcqd0",
    qty: 1,
    freeShipping: true,
    available: "in Stock",
    title: "Modern Bookshelf",
    type: "kitchen",
    colors: ["red", "blue"],
    rate: 3,
    img: require("./Img/tewelve.jpg"),
    price: 369.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 16,
    brand: "Ikea",
    sku: "RecZkNf2kwmdBcqd0",
    qty: 1,
    freeShipping: true,
    available: "in Stock",
    title: "Modern Bookshelf",
    type: "bedroom",
    colors: ["blue", "green"],
    rate: 3,
    img: require("./Img/product13.jpg"),
    price: 329.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 17,
    available: "in Stock",
    qty: 1,
    brand: "caressa",
    freeShipping: false,
    sku: "RecZkNf2kwmdBcqd0",
    title: "Modern Bookshelf",
    type: "kids",
    rate: 3,
    colors: ["red"],
    img: require("./Img/product14.jpg"),
    price: 391.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 18,
    brand: "caressa",
    sku: "RecZkNf2kwmdBcqd0",
    qty: 1,
    available: "in Stock",
    title: "Modern Bookshelf",
    type: "bedroom",
    colors: ["red", "blue", "green"],
    rate: 3,
    img: require("./Img/product15.jpg"),
    price: 2199.99,
    freeShipping: true,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 19,
    brand: "liddy",
    sku: "RecZkNf2kwmdBcqd0",
    qty: 1,
    title: "Modern Bookshelf",
    colors: ["red", "blue", "green"],
    type: "bedroom",
    rate: 3,
    available: "in Stock",
    img: require("./Img/product16.jpg"),
    price: 399.99,
    freeShipping: false,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 20,
    sku: "RecZkNf2kwmdBcqd0",
    qty: 1,
    available: "in Stock",
    title: "Modern Bookshelf",
    colors: ["red", "blue", "green"],
    type: "dining",
    freeShipping: false,
    rate: 3,
    img: require("./Img/product17.jpg"),
    price: 399.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 21,
    brand: "liddy",
    sku: "RecZkNf2kwmdBcqd0",
    qty: 1,
    freeShipping: false,
    available: "in Stock",
    title: "Modern Bookshelf",
    type: "dining",
    colors: ["red", "blue", "green"],
    rate: 3,
    img: require("./Img/product-18.jpg"),
    price: 909.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 22,
    brand: "Ikea",
    sku: "RecZkNf2kwmdBcqd0",
    qty: 1,
    available: "in Stock",
    title: "Modern Bookshelf",
    type: "dining",
    colors: ["red", "purple"],
    rate: 3,
    freeShipping: false,
    img: require("./Img/product-19.jpg"),
    price: 999.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 23,
    qty: 1,
    brand: "liddy",
    sku: "RecZkNf2kwmdBcqd0",
    freeShipping: true,
    colors: ["red", "green"],
    available: "in Stock",
    title: "Modern Bookshelf",
    type: "dining",
    rate: 3,
    img: require("./Img/product-20.jpg"),
    price: 499.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 24,
    available: "in Stock",
    qty: 1,
    colors: ["green"],
    sku: "RecZkNf2kwmdBcqd0",
    brand: "marcos",
    title: "Modern Bookshelf",
    type: "dining",
    freeShipping: true,
    rate: 3,
    img: require("./Img/product-21.jpg"),
    price: 199.99,
    summary:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
];

export default Data;
